name: Trivy → DefectDojo POC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan via Central Trivy Server
        run: |
          trivy fs \
            --server http://13.48.57.189:4954 \
            --format json \
            --output trivy-report.json \
            .

      - name: Upload results to DefectDojo
        env:
          DOJO_URL: ${{ secrets.DOJO_URL }}
          DOJO_API_KEY: ${{ secrets.DOJO_API_KEY }}
        run: |
          curl -X POST "$DOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DOJO_API_KEY" \
            -F "scan_type=Trivy Scan" \
            -F "file=@trivy-report.json" \
            -F "product_name=DevSecOps-POC" \
            -F "engagement_name=GitHub-Trivy"
